/* =========================================================
   FINRISE ASSET
   REAL SUPABASE DEPOSIT FLOW
========================================================= */

document.addEventListener("DOMContentLoaded", async () => {
    const section = document.getElementById("deposit");
    if (!section) return;

    const amountInput = document.getElementById("depositAmount");
    const depositBtn = document.getElementById("depositBtn");
    const balanceEl = document.getElementById("depositBalance");
    const historyEl = document.getElementById("depositHistory");
    const networkEl = document.getElementById("depositNetwork");
    const methods = [...section.querySelectorAll(".deposit-method")];

    // The database stores the payment reference so an administrator can
    // reconcile the user's payment before approving the deposit.
    let referenceInput = document.getElementById("depositReference");
    if (!referenceInput && depositBtn) {
        const wrap = document.createElement("div");
        wrap.className = "deposit-form-group";
        wrap.innerHTML = `
            <div class="deposit-label-row">
                <label for="depositReference">Payment Reference</label>
                <span>Required</span>
            </div>
            <input type="text" id="depositReference" maxlength="120"
                placeholder="Bank transfer reference / crypto transaction hash"
                autocomplete="off" style="width:100%;box-sizing:border-box;">
            <small style="display:block;margin-top:7px;opacity:.7;">
                Enter the reference or transaction hash generated by your payment.
            </small>
        `;
        depositBtn.parentNode?.insertBefore(wrap, depositBtn);
        referenceInput = wrap.querySelector("#depositReference");
    }
    let selectedMethod = methods.find(x => x.classList.contains("active"))?.dataset.method || "crypto";

    const money = value => new Intl.NumberFormat("en-NG", {
        style: "currency", currency: "NGN", minimumFractionDigits: 2
    }).format(Number(value) || 0);

    const escape = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));

    function selectMethod(method) {
        selectedMethod = method;
        methods.forEach(button => button.classList.toggle("active", button.dataset.method === method));
        document.getElementById("cryptoPayment")?.classList.toggle("active", method === "crypto" || method === "usdt");
        document.getElementById("networkPayment")?.classList.toggle("active", method === "usdt");
        document.getElementById("bankPayment")?.classList.toggle("active", method === "bank");

        if (networkEl) {
            networkEl.required = method === "usdt";
            if (method !== "usdt") networkEl.value = "";
        }

        if (referenceInput) {
            referenceInput.placeholder = method === "crypto"
                ? "Crypto transaction hash / TXID"
                : method === "usdt"
                    ? "USDT transaction hash / TXID"
                    : "Bank transfer reference";
        }
    }

    methods.forEach(button => button.addEventListener("click", () => selectMethod(button.dataset.method || "crypto")));

    async function load() {
        const [{ wallet }, { deposits }] = await Promise.all([getCurrentWallet(), getUserDeposits()]);
        if (balanceEl) balanceEl.textContent = money(wallet?.available_balance);
        if (!historyEl) return;

        if (!deposits?.length) {
            historyEl.innerHTML = '<div class="empty-state">No deposits yet.</div>';
            return;
        }

        historyEl.innerHTML = deposits.map(item => `
            <div class="deposit-history-item">
                <div>
                    <strong>${escape(item.method || "Deposit")}</strong>
                    <small>${new Date(item.created_at).toLocaleString()}</small>
                </div>
                <div>
                    <strong>${money(item.amount)}</strong>
                    <small class="status-${escape(item.status)}">${escape(item.status)}</small>
                </div>
            </div>
        `).join("");
    }

    depositBtn?.addEventListener("click", async () => {
        const amount = Number(amountInput?.value);
        const reference = String(referenceInput?.value || "").trim();

        if (!Number.isFinite(amount) || amount < 50) {
            alert("Minimum deposit is ₦50.");
            return;
        }

        if (!["crypto", "usdt", "bank"].includes(selectedMethod)) {
            alert("Please select a valid deposit method.");
            return;
        }

        if (selectedMethod === "usdt" &&
            !["TRC20", "ERC20", "BEP20"].includes(String(networkEl?.value || ""))) {
            alert("Please select a valid USDT network: TRC20, ERC20 or BEP20.");
            networkEl?.focus();
            return;
        }

        if (selectedMethod !== "usdt" && networkEl) {
            networkEl.value = "";
        }

        if (!reference || reference.length < 4) {
            alert("Enter your payment reference or transaction hash before submitting.");
            referenceInput?.focus();
            return;
        }

        const oldText = depositBtn.textContent;
        depositBtn.disabled = true;
        depositBtn.textContent = "Submitting...";

        try {
            const { error } = await submitDeposit({
                amount,
                currency: "NGN",
                method: selectedMethod,
                network: networkEl?.value || null,
                reference
            });
            if (error) throw error;

            alert("Deposit submitted successfully. It will remain pending until an administrator approves it.");
            if (amountInput) amountInput.value = "";
            if (referenceInput) referenceInput.value = "";
            await load();
            document.dispatchEvent(new Event("finrise:refresh-dashboard"));
        } catch (error) {
            console.error("Deposit submission failed:", error);
            const message = String(error?.message || "");
            if (/duplicate|unique|reference/i.test(message)) {
                alert("That payment reference has already been submitted. Please use the correct unique transaction reference.");
            } else if (/check constraint|amount|currency|method|network/i.test(message)) {
                alert(message);
            } else {
                alert("Unable to submit deposit. Please verify your payment details and try again.");
            }
        } finally {
            depositBtn.disabled = false;
            depositBtn.textContent = oldText;
        }
    });

    document.getElementById("copyWallet")?.addEventListener("click", async () => {
        const input = document.getElementById("walletAddress");
        if (!input) return;
        try {
            await navigator.clipboard.writeText(input.value);
            alert("Wallet address copied.");
        } catch { input.select(); document.execCommand("copy"); }
    });

    try {
        await getSupabase();
        selectMethod(selectedMethod);
        await load();
    } catch (error) {
        console.error(error);
    }
});
